version: 0.0
os: linux
files:
  - source: target/nextwork-web-project.war   # Path relative to package root
    destination: /usr/share/tomcat/webapps/   # Target on EC2
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
